diary/urls.py
from django.urls import path
from diary.views import (
                            IndexView,
                            PostDetailView,
                            CategoryPostView,
                            TagPostView,
                            CategoryListView,
                            TagListView,
                            SearchPostView,
                        )


app_name = 'diary'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    # path('post/<str:category_slug>/', PostDetailView.as_view(), name='post_detail'),
    path('category/<str:category_slug>/',CategoryPostView.as_view(), name='category_post'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('search/', SearchPostView.as_view(), name='search_post'),
]

djpj/urls.py
from django.contrib import admin
from django.urls import path, include    # edit
from django.conf import settings    # add:media
from django.conf.urls.static import static    # add:media
# from django.contrib.staticfiles.urls import static #add:開発モード時静的ファイルを配信
from .feeds import LatestPostsFeed    # add:feed(rss)
from django.contrib.sitemaps.views import sitemap    # add:sitemap
from .sitemaps import DiaryPostSitemap, StaticViewSitemap    # add:sitemap
from django.contrib.flatpages.sitemaps import FlatPageSitemap    # add:flatpages

# add:sitemap
sitemaps = {
    'diary': DiaryPostSitemap,
    'static': StaticViewSitemap,
    'flatpages': FlatPageSitemap,    # add:flatpages
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),    # add:app
    path('latest/feed/', LatestPostsFeed()),    # add:feed(rss)
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),    # add:sitemap
    path('pages/', include('django.contrib.flatpages.urls')),    # add:flatpages
]

#add:media
#🔗https://docs.djangoproject.com/ja/2.2/howto/static-files/#serving-files-uploaded-by-a-user-during-development
if settings.DEBUG: # =True
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name      = models.CharField(max_length=255)
    slug      = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name      = models.CharField(max_length=255)
    slug      = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    category     = models.ForeignKey(Category, on_delete=models.PROTECT)
    tags         = models.ManyToManyField(Tag, blank=True)
    title        = models.CharField(max_length=255)
    description  = models.TextField(blank=True)
    content      = models.TextField()
    created_at   = models.DateTimeField(auto_now_add=True)
    updated_at   = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public    = models.BooleanField(default=False)
    image        = models.ImageField(upload_to='post_images/', null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'pk:{self.pk} title:{self.title} created_at:{self.created_at}'


class ContentImage(models.Model):
    post          = models.ForeignKey(Post, on_delete=models.PROTECT)
    content_image = models.ImageField(upload_to='post_content_images/')

diary/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.db.models import Count, Q
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from diary.models import Post, Category, Tag


class PostDetailView(DetailView):
    # queryset = Post.objects.all()
    model       = Post
    paginate_by = 3

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_public and not self.request.user.is_authenticated:
            raise Http404
        return obj


class IndexView(ListView):
    model         = Post
    template_name = 'diary/index.html'
    paginate_by   = 5


class CategoryListView(ListView):
    queryset = Category.objects.annotate(
        num_posts = Count('post', filter=Q(post__is_public=True)))


class TagListView(ListView):
    queryset = Tag.objects.annotate(
        num_posts = Count('post', filter=Q(post__is_public=True)))


class CategoryPostView(ListView):
    model         = Post
    template_name = 'diary/category_post.html'
    paginate_by   = 5

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


class TagPostView(ListView):
    model         = Post
    template_name = 'diary/tag_post.html'
    paginate_by   = 5

    def get_queryset(self):
        tag_slug = self.kwargs['tag_slug']
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        qs = super().get_queryset().filter(tags=self.tag)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context


class SearchPostView(ListView):
    model         = Post
    template_name = 'diary/search_post.html'
    paginate_by   = 5

    def get_queryset(self):
        query = self.request.GET.get('q', None)
        lookups = (
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(category__name__icontains=query) |
            Q(tags__name__icontains=query)
        )
        if query is not None:
            qs = super().get_queryset().filter(lookups).distinct()
            return qs
        qs = super().get_queryset()
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context

diary/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lamg="ja">
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
    {#<!-- Global site tag (gtag.js) - Google Analytics -->#}
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-PX7GBV0QCC"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-PX7GBV0QCC');
    </script>
    <title>{% block title %}djpj{% endblock %}</title>
    {#<!-- [meta] -->#}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="description" content="{% block descriotion %}{% endblock %}">
    <meta name="keywords" content="{% for tag in tags.all %}{{ tag.name }},{% empty %}{% endfor %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {#<!-- OGP -->#}
    <meta property="og:url" content="https://djpj.jp">
    <meta property="og:type" content="website">
    <meta property="og:title" content="{{ post.title }}">
    <meta property="og:description" content="{{ post.description }}">
    <meta property="og:site_name" content="djpj">
    {#<meta property="og:image" content="https://djpj.{{ post.image.url }}">#}
    <meta property="og:image" content="https://jp.heroku.com/assets/wallpapers/python/screen-c49382dd0a34719040755a37358c5fa79543494a387c5dc604f022ef0cfaf18c.png">
    <meta name="twitter:card" content="Summary Card" />
    <meta name="twitter:site" content="{@ツイッターユーザー名}" />
    {#<!-- [link] -->#}
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'diary/img/favicon.ico' %}">
    <link rel="icon" href="{% static 'diary/img/icon.png' %}">
    <link rel="shortcut icon" href="{% static 'diary/img/icon.png' %}">
    <link rel="apple-touch-icon" href="{% static 'diary/img/icon.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'diary/img/icon.png' %}">
    {#<!-- css -->#}
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'diary/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'diary/css/common.css' %}">
    <link rel="stylesheet" href="{% static 'diary/css/common/drawer.css' %}">
    <link rel="stylesheet" href="{% static 'diary/css/common/loading.css' %}">
    {#<!-- Google Tag Manager -->#}
    <!-- <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-TDDTX4F');</script> -->
    {#<!-- End Google Tag Manager -->#}
</head>
<body class="drawer drawer--right">
    {#<!-- Google Tag Manager (noscript) -->#}
    <!-- <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TDDTX4F"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript> -->
    {#<!-- End Google Tag Manager (noscript) -->#}

    {#<!-- loading animation -->#}
    <div id="Loading">
        <div id="load">
            <div>j</div>
            <div>p</div>
            <div>j</div>
            <div>d</div>
            <div>●</div>
        </div>
    </div>

    {#<!-- contents -->#}
    <div class="l-page-wrapper">
        <div id="page" class="l-page">

            {#<!-- contents sections -->#}
            <div class="page-inner">

                {#<!-- header section-->#}
                <div class="l-page__header">
                    <header id="Header">
                        <div class="inner cf">
                            {#<!-- logo -->#}
                            <p class="logo"><a href="/"><img src="{% static 'diary/img/logo.png' %}" alt="djpj"></a></p>
                            {#<!-- hunberger -->#}
                            <p class="menu">
                                <a class="menu-trigger drawer-toggle drawer-hamburger" id="menu-trigger12" href="#">
                                    <span></span><span></span><span></span>
                                </a>
                            </p>
                            {#<!-- navigation section -->#}
                            <nav class="drawer-nav">
                                <ul class="drawer-menu">
                                    {#<!-- Search -->#}
                                    <li class="search">
                                        <form action="{% url 'diary:search_post' %}" method="GET">
                                          <input class="search" type="text" name="q" value="{{ request.GET.q }}" placeholder="Free word Search" aria-label="Search"> <input type="submit" class="search_btn" value="">
                                        </form>
                                    </li>
                                    {#<!-- Category -->#}
                                    {% for category in categories|dictsortreversed:"num_posts"|slice:":7" %}
                                    <li>
                                        <a href="{% url 'diary:category_post' category.slug %}">{{ category.name }} ({{ category.num_posts }})</a>
                                    </li>
                                    {% empty %}
                                    <li><a href="/">カテゴリはありません。</a></li>
                                    {% endfor %}
                                    {#<!-- About -->#}
                                    <li class="about"><a href="/pages/about/">About</a></li>
                                </ul>
                            </nav>
                        </div>
                    </header>
                </div>{#<!-- .l-page__header // -->#}

                {#<!-- ************************ -->#}
                {% block content %}{% endblock %}
                {#<!-- ************************ -->#}

            </div>{#<!-- .page-inner // -->#}

            {#<!-- footer section -->#}
            <div class="l-page__footer">
                <footer id="Fotter">
                    <div class="inner cf">
                        <p class="logo"><a href="/"><img src="{% static 'diary/img/logo.png' %}" alt="djpj"></a></p>
                        <div class="link">
                            <ul class="sns account">
                                {#<!-- facebook -->#}
                                <!-- <li class="snsicon"><a href="https://www.facebook.com/" alt="" target="_blank"><i class="fab fa-fw fa-facebook-f"></i></a></li> -->
                                {#<!-- twitter -->#}
                                <li class="snsicon">
                                    <a href="https://twitter.com/" alt="Twitterへのリンク" target="_blank">
                                        <i class="fab fa-fw fa-twitter"></i>
                                    </a>
                                </li>
                                {#<!-- github -->#}
                                <li class="snsicon">
                                    <a href="" alt="Githubへのリンク" target="_blank">
                                        <i class="fab fa-fw fa-github"></i>
                                    </a>
                                </li>
                                {#<!-- kaggle -->#}
                                <li class="snsicon">
                                    <a href="" alt="Kaggleへのリンク" target="_blank">
                                        <i class="fab fa-fw fa-kaggle"></i>
                                    </a>
                                </li>
                            </ul>
                            <p class="copy">&copy; 2020 djpj</p>
                        </div>
                    </div>
                </footer>
            </div>{#<!-- .l-page__footer // -->#}

        </div>{#<!-- .l-page // -->#}
    </div>{#<!-- .l-page-wrapper // -->#}

    {#<!-- [script] -->#}
    <script src="{% static 'diary/js/vendor.js' %}"></script>
    <script src="{% static 'diary/js/common.js' %}"></script>
    <script src="{% static 'diary/js/common/imagesloaded.js' %}"></script>
    <script src="{% static 'diary/js/common/iscroll.js' %}"></script>{#<!-- スクロールー調整-->#}
    <script src="{% static 'diary/js/common/drawer.min.js' %}"></script>{#<!-- ドロワー調整-->#}
    <script src="{% static 'diary/js/common/heightLine.js' %}"></script>{#<!-- 高さ調整-->#}
</body>
</html>

diary/templates/diary/category_list.html
<h1>カテゴリ一覧</h1>
<ul>
  {% for category in object_list %}
  <li><a href="{% url 'diary:category_post' category.slug %}">{{ category.name }} ({{ category.num_posts }})</a></li>
  {% empty %}
  <li>カテゴリはありません。</li>
  {% endfor %}
</ul>

diary/templates/diary/category_post.html
{% extends "base.html" %}

{% block title %}「{{ category.name }}」投稿一覧 | {{ block.super }}{% endblock %}
{% block description %}{% endblock %}
{% block content %}
{# <!-- カテゴリ別（投稿一覧） --> #}

{% include "diary/snippets/list_detail.html" %}

{% endblock %}

diary/templates/diary/index.html
{% extends "base.html" %}

{% block title %}{{ block.super }}{% endblock %}
{% block description %}{% endblock %}
{% block content %}
{# <!-- 投稿一覧 --> #}

{% include "diary/snippets/list_detail.html" %}

{% endblock %}

diary/templates/diary/post_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}{{ object.title}} | {{ block.super }}{% endblock %}
{% block description %}{% endblock %}
{% block content%}
{#<!-- detail css -->#}
<link rel="stylesheet" href="{% static 'diary/css/details.css' %}">

{# <!-- main sections --> #}
<main class="main-area l-wrap">


    <div class="l-panel l-panel--mv">
        <div class="l-panel__item l-panel__item--large">
            <article class="m-card m-card--large">
                <div class="m-card__body">
                    <h1 class="hdg">{{ object.title }}</h1>
                    <p class="date">
                        <i class="fas fa-clock"></i> {{ object.published_at|date }}
                        <span>/</span>
                        <i class="fas fa-folder"></i> {{ object.category.name }}
                    </p>
                </div>
                <div class="m-card__img">
                    {% if post.image %}
                    <span class="img__bg" style="background-image:url({{ post.image.url }})"></span>
                    {% else %}
                    <span class="img__bg" style="background-image:url(https://jp.heroku.com/assets/wallpapers/python/screen-c49382dd0a34719040755a37358c5fa79543494a387c5dc604f022ef0cfaf18c.png)"></span>
                    {% endif %}
                </div>
            </article>{# <!-- .m-card // --> #}
        </div>{# <!-- .l-panel__item // --> #}
    </div>{# <!-- .l-panel // --> #}

    {# <!-- bread SNS index --> #}
    <div class="detail l-wrap">
        <div class="l-panel">
            <div class="content inner">

                {# <!-- パンクズリスト --> #}
                <div class="l-breadcrumbs">
                    <a href="/"><i class="fas fa-home"></i>djpj</a> ＞
                    <a href="/category/{{ object.category.slug }}"><i class="fas fa-folder"></i> {{ object.category.name }}</a> ＞
                    <span class="title"><i class="fas fa-sticky-note"></i> {{ object.title }}<span>
                </div>

                {% include "diary/snippets/sns.html" %}

                {# <!-- 記事導入（description） --> #}
                <div class="sec"><p>{{ object.description }}</p></div>

            </div>{# <!-- .inner // --> #}
        </div>{# <!-- .l-panel // --> #}
    </div>{# <!-- .l-wrap // --> #}

     {# 広告 {% include "diary/snippets/ad.html" %} #}

    {# <!-- post contents --> #}
    <div class="detail l-wrap">
        <div class="l-panel">
            <div class="content inner">
                {# <!-- 記事 --> #}
                {{ object.content|safe }}

                {% include "diary/snippets/sns.html" %}

                {# <!-- タグリスト --> #}
                <div class="tag">
                    <ul class="cp_tag">
                        {% for tag in object.tags.all %}
                        <li><a href="{% url 'diary:tag_post' tag.slug %}">#{{ tag.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>{# <!-- .inner // --> #}
        </div>{# <!-- .l-panel // --> #}
    </div>{# <!-- .l-wrap // --> #}

     {# 広告 {% include "diary/snippets/ad.html" %} #}

    {# <!-- post recommend --> #}
    <div class="l-wrap recomend">
        <h4 class="hdg">Recommend</h4>
        <div class="l-panel">
            {% for post in object_list|slice:"1:" %}
            {% if user.is_authenticated or post.is_public %}
            <div class="l-panel__item heightLine">
                <article class="m-card">
                    <a href="{% url 'diary:post_detail' post.id %}">
                        {% if post.image %}
                        <div class="m-card__img">
                            <span class="img__bg" style="background-image:url({{ post.image.url }})"></span>
                        </div>
                        {% endif %}
                        <div class="m-card__body">
                            <p class="date">
                                <i class="fas fa-clock"></i> {{ post.published_at|date }}<span>/</span>
                                <i class="fas fa-folder"></i> {{ post.category.name }}</p>
                            <h3 class="hdg">{% if not post.is_public %}[下書き] {% endif %}{{ post.title }}</h3>
                            <p class="detail u-img--pc">{{ post.description }}</p>
                        </div>
                    </a>
                </article>
            </div>{#<!-- .l-panel__item // -->#}
            {% endif %}
            {% empty %}
            <div class="l-panel__item heightLine">
                <article class="m-card">
                    <div class="m-card__body">
                        <h3>Comeing soon...</h3>
                    </div>{#<!-- .m-card__body // -->#}
                </article>{#<!-- .m-card // -->#}
            </div>{#<!-- .l-panel__item // -->#}
            {% endfor %}

        </div>{# <!-- .l-panel // --> #}

    </div>{# <!-- .l-wrap // --> #}

</main>{# <!-- .main-area // --> #}

{#<!-- detials script  (シンタックスハイライト)-->#}
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'diary/js/sh/shCore.js' %}"></script>
<script type="text/javascript" src="{% static 'diary/js/sh/shBrushBash.js' %}"></script>
<script type="text/javascript" src="{% static 'diary/js/sh/shAutoloader.js' %}"></script>
<script type="text/javascript">
    $(function(){
        function path(){
            var args = arguments,
            result = [];
            for (var i = 0; i < args.length; i++) result.push(args[i].replace('@', '{% static 'diary/js/sh/' %}'));
            return result
        };
        SyntaxHighlighter.autoloader.apply(null, path(
            'applescript@shBrushAppleScript.js',
            'actionscript3as3@shBrushAS3.js',
            'bash shell @shBrushBash.js',
            'coldfusion cf @shBrushColdFusion.js',
            'cpp c @shBrushCpp.js',
            'c# c-sharp csharp @shBrushCSharp.js',
            'css @shBrushCss.js',
            'delphi pascal @shBrushDelphi.js',
            'diff patch pas @shBrushDiff.js',
            'erl erlang @shBrushErlang.js',
            'groovy @shBrushGroovy.js',
            'java @shBrushJava.js',
            'jfx javafx @shBrushJavaFX.js',
            'js jscript javascript @shBrushJScript.js',
            'perl pl @shBrushPerl.js',
            'php @shBrushPhp.js',
            'text plain @shBrushPlain.js',
            'py python @shBrushPython.js',
            'ruby rails ror rb @shBrushRuby.js',
            'sass scss @shBrushSass.js',
            'scala @shBrushScala.js',
             'sql @shBrushSql.js',
             'vb vbnet @shBrushVb.js',
             'xml xhtml xslt html @shBrushXml.js'));
        SyntaxHighlighter.all();
    });
</script>
<link type="text/css" rel="stylesheet" href="{% static 'diary/js/sh/shCore.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'diary/js/sh/shThemeMidnight.css' %}" />

{% endblock%}

diary/templates/diary/search_post.html
{% extends "base.html" %}

{% block title %}{% if query %}{{ query }}{% endif %} | {{ block.super }}{% endblock %}
{% block description %}検索ワード「{% if query %}{{ query }}{% endif %}」での検索結果ページです。{% endblock %}
{% block content %}
{# <!-- 検索結果別（投稿一覧） --> #}

{#<!-- 検索結果 -->#}
<div class="main-area l-wrap">
「{% if query %}{{ query }}{% endif %}」の検索結果 {{ page_obj.start_index }}-{{ page_obj.end_index }}件（{{ paginator.count }}件）
</div>

{% include "diary/snippets/list_detail.html" %}

{% endblock %}

diary/templates/diary/snippets/list_detail.html
{#<!-- main 1 section -->#}
<div class="main-area l-wrap">
    <div class="l-panel l-panel--mv">

        {% for post in object_list|slice:":1" %}
        {% if user.is_authenticated or post.is_public %}
        <div class="l-panel__item l-panel__item--large">
            <article class="m-card m-card--large">
                <a href="{% url 'diary:post_detail' post.id %}">
                    <div class="m-card__img">
                        {% if post.image %}
                        <span class="img__bg" style="background-image:url({{ post.image.url }})"></span>
                        {% else %}
                        <span class="img__bg" style="background-image:url(https://jp.heroku.com/assets/wallpapers/python/screen-c49382dd0a34719040755a37358c5fa79543494a387c5dc604f022ef0cfaf18c.png)"></span>
                        {% endif %}
                    </div>
                    <div class="m-card__body">
                        <p class="date">
                            <i class="fas fa-clock"></i> {{ post.published_at|date }}
                            <span>/</span>
                            <i class="fas fa-folder"></i> {{ post.category.name }}
                        </p>
                        <h3 class="hdg">{% if not post.is_public %}[下書き] {% endif %}{{ post.title }}</h3>
                    </div>
                </a>
            </article>
        </div>{#<!-- .l-panel__item // -->#}
        {% endif %}
        {% endfor %}

    </div>{#<!-- .l-panel // -->#}
</div>{#<!-- .main-area // -->#}


{#<!-- main 2 section -->#}
<div class="l-page__main">

    {# 広告 {% include "diary/snippets/ad.html" %} #}

    {#<!-- posts section -->#}
    <div class="item-area l-wrap">
        <div class="l-panel">

            {% for post in object_list|slice:"1:" %}
            {% if user.is_authenticated or post.is_public %}
            <div class="l-panel__item heightLine">
                <article class="m-card">
                    <a href="{% url 'diary:post_detail' post.id %}">
                        <div class="m-card__img">
                            {% if post.image %}
                            <span class="img__bg" style="background-image:url({{ post.image.url }})"></span>
                            {% else %}
                            <span class="img__bg" style="background-image:url(https://jp.heroku.com/assets/wallpapers/python/screen-c49382dd0a34719040755a37358c5fa79543494a387c5dc604f022ef0cfaf18c.png)"></span>
                            {% endif %}
                        </div>
                        <div class="m-card__body">
                            <p class="date">
                                <i class="fas fa-clock"></i> {{ post.published_at|date }}
                                <span>/</span>
                                <i class="fas fa-folder"></i> {{ post.category.name }}
                            </p>
                            <h3 class="hdg">{% if not post.is_public %}[下書き] {% endif %}{{ post.title }}</h3>
                            <p class="detail u-img--pc">{{ post.description }}</p>
                        </div>
                    </a>
                </article>
            </div>{#<!-- .l-panel__item // -->#}
            {% endif %}
            {% empty %}
            <div class="l-panel__item heightLine">
                <article class="m-card">
                    <div class="m-card__body">
                        <h3>まだ投稿はありません。</h3>
                    </div>
                </article>
            </div>{#<!-- .l-panel__item // -->#}
            {% endfor %}

        </div>{#<!-- .l-panel // -->#}
    </div>{#<!-- .l-wrap // -->#}

    {% include "diary/snippets/pagination.html" %}

</div>{#<!-- .l-page__main // -->#}

diary/templates/diary/snippets/sns.html
{#<!-- SNSシェア -->#}
<div class="sns">
    <ul class="sns-list">
        {#<!-- Twitter -->#}
        <li class="tw">
            <a id="ga-list-twitter-share" class="twitter btn" href="http://twitter.com/share?url=http://www.root.com/{% url 'diary:post_detail' post.id %}&amp;text={{ object.title }}&amp;via=&amp;related=" target="_blank" onclick="window.open(this.href, 'FBwindow', 'width=650, height=450, menubar=no, toolbar=no, scrollbars=yes'); return false;">Twitter</a>
        </li>
        {#<!-- Facebook -->#}
        <li class="fb">
            <a id="ga-list-fb-share" class="fb btn" href="http://www.facebook.com/share.php?u=http://www.root.com/{% url 'diary:post_detail' post.id%}" onclick="window.open(this.href, 'FBwindow', 'width=650, height=450, menubar=no, toolbar=no, scrollbars=yes'); return false;">Facebook</a>
        </li>
        {#<!-- RSS -->#}
        <li class="rss"><a href="/latest/feed/">RSS</a></li>
    </ul>
</div>

diary/templates/diary/tag_list.html
<h1>タグ一覧</h1>
<ul>
  {% for tag in object_list %}
  <li><a href="{% url 'diary:tag_post' tag.slug %}">{{ tag.name }} ({{ tag.num_posts }})</a></li>
  {% empty %}
  <li>タグはありません。</li>
  {% endfor %}
</ul>

diary/templates/diary/tag_post.html
{% extends "base.html" %}

{% block title %}「#{{ tag.name }}」投稿一覧 | {{ block.super }}{% endblock %}
{% block description %}{% endblock %}
{% block content %}
{# <!-- タグ別（投稿一覧） --> #}

{% include "diary/snippets/list_detail.html" %}

{% endblock %}